# Generated by Django 4.2.3 on 2023-07-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0006_order_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
    ]
